#!/usr/bin/env ruby

require "#{Dir.pwd.gsub(/\/apps.*$/, '')}/apps/contingent/tools/context"

require 'test/unit'
require 'test/unit/ui/console/testrunner'

for file in `ls tests/test.d`.split do
	require "tests/test.d/#{file}"
end

def init_db
	`mysql -ucontingent -pfaretheewell contingent-test <tests/contingent-test-base.sql`
	puts 'Database reinit done'
end

#init_db
Test::Unit::UI::Console::TestRunner.run(Test_AuthUser.suite)
Test::Unit::UI::Console::TestRunner.run(Test_Order.suite)
Test::Unit::UI::Console::TestRunner.run(Test_Group.suite)
