##
## Generated by details-generator. Do not edit!
##

require 'interface/order/details/common'
require 'expression'

class DetailsForCitizenshipSwitchingOrder
	extend DetailsCommon

	CONDITIONS = [
		DetailsCommon::Condition.new('was_contract', {"student:study_type_id"=>Classifier::StudyType::CONTRACT}),
		DetailsCommon::Condition.new('became_contract', {"order:study_type_id"=>Classifier::StudyType::CONTRACT}),
		DetailsCommon::Condition.new('contract', {"study_type_id"=>Classifier::StudyType::CONTRACT}),
		DetailsCommon::Condition.new('foreign', {"citizenship_id"=>[4, 5, 6, 7]}),
		DetailsCommon::Condition.new('disabled', {"category"=>:disabled})
	]

	def self.has_order?
		true
	end

	def self.init_order(o)
		attributes = o.attributes.dup
		attributes['citizenship_id'] = 1
		attributes['citizenship'] = 2
		attributes['category'] = Proc.new { Expression.new('category & ~1') }.call
		attributes.each_pair { |k,v| o.attributes[k] = v }
		o.save
	end

	def self.fix_order(o)
		attributes = o.attributes.dup
		attributes['study_type_id'] ||= Proc.new { first_value(Classifier::StudyType) }.call
		attributes
	end

	def self.render_order(o, tmpl)
		attributes = fix_order(o)
		tmpl.study_type_id = attributes['study_type_id']
	end

	def self.save_order(o, params)
		attributes = o.attributes.dup
		attributes['study_type_id'] = params["study_type_id_id"].to_s.split(':')[0].to_i
		attributes.each_pair { |k,v| o.attributes[k] = v }
		o.save
	end

	def self.has_student?(paragraph)
		[0].member? paragraph
	end
	
	def self.init_student(o, eid, paragraph)
		attributes = o.get_student_attributes(eid)
		case paragraph
		when 0
		end
		o.set_student_attributes(eid, attributes)
	end
	
	def self.fix_student(o, eid, paragraph, attributes)
		attributes = attributes.dup
		case paragraph
		when 0
			attributes['country_id'] ||= Proc.new { first_value(Classifier::Country) }.call
			attributes['group_id'] ||= Proc.new { Student.load(eid).group.oid }.call.to_i
		end
		attributes
	end
	
	def self.render_student(o, eid, paragraph, tmpl)
		attributes = fix_student(o, eid, paragraph, o.get_student_attributes(eid))
		case paragraph
		when 0
			tmpl.country_id = attributes['country_id']
			tmpl.contract = attributes['contract']
			tmpl.assignment = attributes['assignment']
			tmpl.previous_agreement = attributes['previous_agreement']
			tmpl.agreement = attributes['agreement']
			tmpl.start_at = attributes['start_at']
			tmpl.card_number = attributes['card_number']
			tmpl.group_id = attributes['group_id']
		end
	end
	
	def self.save_student(o, eid, paragraph, params)
		attributes = o.get_student_attributes(eid)
		case paragraph
		when 0
			attributes['country_id'] = params["country_id_id"].to_s.split(':')[0].to_i
			attributes['contract'] = Document.new(params["contract_date"].to_d, params["contract_num"])
			attributes['assignment'] = Document.new(params["assignment_date"].to_d, params["assignment_num"])
			attributes['previous_agreement'] = Document.new(params["previous_agreement_date"].to_d, params["previous_agreement_num"])
			attributes['agreement'] = Document.new(params["agreement_date"].to_d, params["agreement_num"])
			attributes['start_at'] = params["start_at"].to_d
			attributes['card_number'] = params["card_number"]
			attributes['group_id'] = params["group_id"].to_i
		end
		o.set_student_attributes(eid, attributes)
	end

	def self.has_group?(paragraph)
		[].member? paragraph
	end
end
