##
## Generated by details-generator. Do not edit!
##

require 'interface/order/details/common'
require 'expression'

class DetailsForDormitoryOccupancyOrder
	extend DetailsCommon

	CONDITIONS = [
		DetailsCommon::Condition.new('first_term', {"student:current_term_number"=>1}),
		DetailsCommon::Condition.new('contract', {"study_type_id"=>Classifier::StudyType::CONTRACT}),
		DetailsCommon::Condition.new('foreign', {"citizenship_id"=>[4, 5, 6, 7]}),
		DetailsCommon::Condition.new('disabled', {"category"=>:disabled})
	]

	def self.has_order?
		true
	end

	def self.init_order(o)
		attributes = o.attributes.dup
		attributes['hide_study_type'] = 1
		attributes['dormitory'] = 1
		attributes.each_pair { |k,v| o.attributes[k] = v }
		o.save
	end

	def self.fix_order(o)
		attributes = o.attributes.dup
		attributes
	end

	def self.render_order(o, tmpl)
		attributes = fix_order(o)
		tmpl.resolution = attributes['resolution']
	end

	def self.save_order(o, params)
		attributes = o.attributes.dup
		attributes['resolution'] = Document.new(params["resolution_date"].to_d, params["resolution_num"])
		attributes.each_pair { |k,v| o.attributes[k] = v }
		o.save
	end

	def self.has_student?(paragraph)
		[0].member? paragraph
	end
	
	def self.init_student(o, eid, paragraph)
		attributes = o.get_student_attributes(eid)
		case paragraph
		when 0
		end
		o.set_student_attributes(eid, attributes)
	end
	
	def self.fix_student(o, eid, paragraph, attributes)
		attributes = attributes.dup
		case paragraph
		when 0
			attributes['dormitory_num'] ||= Proc.new { { 'ИУ' => 5, 'РЛ' => 5, 'БМТ' => 5, 'МТ' => 4, 'РК' => 9, 'Э' => 10, 'СМ' => 11 }[o.faculty.name] || 5 }.call.to_i
		end
		attributes
	end
	
	def self.render_student(o, eid, paragraph, tmpl)
		attributes = fix_student(o, eid, paragraph, o.get_student_attributes(eid))
		case paragraph
		when 0
			tmpl.dormitory_num = attributes['dormitory_num']
		end
	end
	
	def self.save_student(o, eid, paragraph, params)
		attributes = o.get_student_attributes(eid)
		case paragraph
		when 0
			attributes['dormitory_num'] = params["dormitory_num"].to_i
		end
		o.set_student_attributes(eid, attributes)
	end

	def self.has_group?(paragraph)
		[].member? paragraph
	end
end
