##
## Generated by details-generator. Do not edit!
##

require 'interface/order/details/common'
require 'expression'

class DetailsForEnrollmentOrder
	extend DetailsCommon

	CONDITIONS = [
		DetailsCommon::Condition.new('special', {"special_enrollment_code"=>Empty.new(false)}),
		DetailsCommon::Condition.new('contract', {"study_type_id"=>Classifier::StudyType::CONTRACT}),
		DetailsCommon::Condition.new('foreign', {"citizenship_id"=>[4, 5, 6, 7]}),
		DetailsCommon::Condition.new('disabled', {"category"=>:disabled})
	]

	def self.has_order?
		true
	end

	def self.init_order(o)
		attributes = o.attributes.dup
		attributes['student_state_id'] = Proc.new { Classifier::StudentState::STUDYING }.call.to_i
		attributes.each_pair { |k,v| o.attributes[k] = v }
		o.save
	end

	def self.fix_order(o)
		attributes = o.attributes.dup
		attributes['study_type_id'] ||= Proc.new { first_value(Classifier::StudyType) }.call
		attributes['degree_code'] ||= Proc.new { first_value(Classifier::Degree) }.call
		attributes
	end

	def self.render_order(o, tmpl)
		attributes = fix_order(o)
		tmpl.resolution = attributes['resolution']
		tmpl.approval = attributes['approval']
		tmpl.enrollment_date = attributes['enrollment_date']
		tmpl.study_type_id = attributes['study_type_id']
		tmpl.degree_code = attributes['degree_code']
	end

	def self.save_order(o, params)
		attributes = o.attributes.dup
		attributes['resolution'] = Document.new(params["resolution_date"].to_d, params["resolution_num"])
		attributes['approval'] = Document.new(params["approval_date"].to_d, params["approval_num"])
		attributes['enrollment_date'] = params["enrollment_date"].to_d
		attributes['study_type_id'] = params["study_type_id_id"].to_s.split(':')[0].to_i
		attributes['degree_code'] = params["degree_code_code"]
		attributes.each_pair { |k,v| o.attributes[k] = v }
		o.save
	end

	def self.has_student?(paragraph)
		[0].member? paragraph
	end
	
	def self.init_student(o, eid, paragraph)
		attributes = o.get_student_attributes(eid)
		case paragraph
		when 0
		end
		o.set_student_attributes(eid, attributes)
	end
	
	def self.fix_student(o, eid, paragraph, attributes)
		attributes = attributes.dup
		case paragraph
		when 0
			attributes['gender_id'] ||= Proc.new { 1 }.call
			attributes['citizenship_id'] ||= Proc.new { 1 }.call
			attributes['profession_code'] ||= Proc.new { first_value(Classifier::Profession) }.call
			attributes['specialization_code'] ||= Proc.new { '00' }.call
			attributes['country_id'] ||= Proc.new { first_value(Classifier::Country) }.call
		end
		attributes
	end
	
	def self.render_student(o, eid, paragraph, tmpl)
		attributes = fix_student(o, eid, paragraph, o.get_student_attributes(eid))
		case paragraph
		when 0
			tmpl.name = attributes['name']
			tmpl.gender_id = attributes['gender_id']
			tmpl.birth_date = attributes['birth_date']
			tmpl.passport = attributes['passport']
			tmpl.citizenship_id = attributes['citizenship_id']
			tmpl.card_number = attributes['card_number']
			tmpl.group_id = attributes['group_id']
			tmpl.profession_code = attributes['profession_code']
			tmpl.specialization_code = attributes['specialization_code']
			tmpl.agreement = attributes['agreement']
			tmpl.country_id = attributes['country_id']
			tmpl.assignment = attributes['assignment']
			tmpl.special_assignment = attributes['special_assignment']
			tmpl.note = attributes['note']
		end
	end
	
	def self.save_student(o, eid, paragraph, params)
		attributes = o.get_student_attributes(eid)
		case paragraph
		when 0
			attributes['name'] = {
				'first' => params["name_first"],
				'last' => params["name_last"],
				'father' => params["name_father"]
			}
			attributes['gender_id'] = params["gender_id_id"].to_s.split(':')[0].to_i
			attributes['birth_date'] = params["birth_date"].to_d
			attributes['passport'] = params["passport"]
			attributes['citizenship_id'] = params["citizenship_id_id"].to_s.split(':')[0].to_i
			attributes['card_number'] = params["card_number"]
			attributes['group_id'] = params["group_id"].to_i
			attributes['profession_code'] = params["profession_code_code"]
			attributes['specialization_code'] = params["specialization_code"]
			attributes['agreement'] = Document.new(params["agreement_date"].to_d, params["agreement_num"])
			attributes['country_id'] = params["country_id_id"].to_s.split(':')[0].to_i
			attributes['assignment'] = Document.new(params["assignment_date"].to_d, params["assignment_num"])
			attributes['special_assignment'] = params["special_assignment"]
			attributes['note'] = params["note"]
		end
		o.set_student_attributes(eid, attributes)
	end

	def self.has_group?(paragraph)
		[].member? paragraph
	end
end
