##
## Generated by details-generator. Do not edit!
##

require 'interface/order/details/common'
require 'expression'

class DetailsForGraduationOrder
	extend DetailsCommon

	CONDITIONS = [
		DetailsCommon::Condition.new('contract', {"study_type_id"=>Classifier::StudyType::CONTRACT}),
		DetailsCommon::Condition.new('foreign', {"citizenship_id"=>[4, 5, 6, 7]}),
		DetailsCommon::Condition.new('disabled', {"category"=>:disabled})
	]

	def self.has_order?
		true
	end

	def self.init_order(o)
		attributes = o.attributes.dup
		attributes['student_state_id'] = Proc.new { Classifier::StudentState::GRADUATED }.call.to_i
		attributes.each_pair { |k,v| o.attributes[k] = v }
		o.save
	end

	def self.fix_order(o)
		attributes = o.attributes.dup
		attributes
	end

	def self.render_order(o, tmpl)
		attributes = fix_order(o)
		tmpl.graduation_date = attributes['graduation_date']
	end

	def self.save_order(o, params)
		attributes = o.attributes.dup
		attributes['graduation_date'] = params["graduation_date"].to_d
		attributes.each_pair { |k,v| o.attributes[k] = v }
		o.save
	end

	def self.has_student?(paragraph)
		[0].member? paragraph
	end
	
	def self.init_student(o, eid, paragraph)
		attributes = o.get_student_attributes(eid)
		case paragraph
		when 0
		end
		o.set_student_attributes(eid, attributes)
	end
	
	def self.fix_student(o, eid, paragraph, attributes)
		attributes = attributes.dup
		case paragraph
		when 0
			attributes['mark'] ||= Proc.new { '' }.call
			attributes['qualification'] ||= Proc.new { 'инженер' }.call
			attributes['diploma_type'] ||= Proc.new { 'С выдачей диплома о высшем профессиональном образовании' }.call
			attributes['country_id'] ||= Proc.new { first_value(Classifier::Country) }.call
		end
		attributes
	end
	
	def self.render_student(o, eid, paragraph, tmpl)
		attributes = fix_student(o, eid, paragraph, o.get_student_attributes(eid))
		case paragraph
		when 0
			tmpl.graduation_thesis = attributes['graduation_thesis']
			tmpl.mark = attributes['mark']
			tmpl.qualification = attributes['qualification']
			tmpl.diploma_type = attributes['diploma_type']
			tmpl.languages = attributes['languages']
			tmpl.protocol = attributes['protocol']
			tmpl.agreement = attributes['agreement']
			tmpl.country_id = attributes['country_id']
			tmpl.passport = attributes['passport']
			tmpl.assignment = attributes['assignment']
		end
	end
	
	def self.save_student(o, eid, paragraph, params)
		attributes = o.get_student_attributes(eid)
		case paragraph
		when 0
			attributes['graduation_thesis'] = params["graduation_thesis"]
			attributes['mark'] = params["mark"]
			attributes['qualification'] = params["qualification"]
			attributes['diploma_type'] = params["diploma_type"]
			attributes['languages'] = params["languages"]
			attributes['protocol'] = Document.new(params["protocol_date"].to_d, params["protocol_num"])
			attributes['agreement'] = Document.new(params["agreement_date"].to_d, params["agreement_num"])
			attributes['country_id'] = params["country_id_id"].to_s.split(':')[0].to_i
			attributes['passport'] = params["passport"]
			attributes['assignment'] = Document.new(params["assignment_date"].to_d, params["assignment_num"])
		end
		o.set_student_attributes(eid, attributes)
	end

	def self.has_group?(paragraph)
		[].member? paragraph
	end
end
