# Generated by generate-wsdl. Do not edit!

module ContingentSOAP
require 'xsd/qname'

# {http://contingent.bmstu.ru/}BaseObject
class BaseObject
  @@schema_type = "BaseObject"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = [["id", ["SOAP::SOAPString", XSD::QName.new(nil, "id")]], ["name", ["SOAP::SOAPString", XSD::QName.new(nil, "name")]]]

  attr_accessor :id
  attr_accessor :name

  def initialize(id = nil, name = nil)
    @id = id
    @name = name
  end
end

# {http://contingent.bmstu.ru/}Person
class Person
  @@schema_type = "Person"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = []

  def initialize
  end
end

# {http://contingent.bmstu.ru/}Student
class Student
  @@schema_type = "Student"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = []

  def initialize
  end
end

# {http://contingent.bmstu.ru/}Classifier
class Classifier
  @@schema_type = "Classifier"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = []

  def initialize
  end
end

# {http://contingent.bmstu.ru/}Order
class Order
  @@schema_type = "Order"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = []

  def initialize
  end
end

# {http://contingent.bmstu.ru/}listOrdersRequest
class ListOrdersRequest
  @@schema_type = "listOrdersRequest"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = [["name", ["SOAP::SOAPString", XSD::QName.new(nil, "name")]], ["dateStart", ["SOAP::SOAPDateTime", XSD::QName.new(nil, "dateStart")]], ["dateEnd", ["SOAP::SOAPDateTime", XSD::QName.new(nil, "dateEnd")]], ["faculty", ["Faculty", XSD::QName.new(nil, "faculty")]]]

  attr_accessor :name
  attr_accessor :dateStart
  attr_accessor :dateEnd
  attr_accessor :faculty

  def initialize(name = nil, dateStart = nil, dateEnd = nil, faculty = nil)
    @name = name
    @dateStart = dateStart
    @dateEnd = dateEnd
    @faculty = faculty
  end
end

# {http://contingent.bmstu.ru/}listStudentsRequest
class ListStudentsRequest
  @@schema_type = "listStudentsRequest"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = [["lastName", ["SOAP::SOAPString", XSD::QName.new(nil, "lastName")]], ["firstName", ["SOAP::SOAPString", XSD::QName.new(nil, "firstName")]], ["middleName", ["SOAP::SOAPString", XSD::QName.new(nil, "middleName")]], ["group", ["SOAP::SOAPString", XSD::QName.new(nil, "group")]], ["cardNumber", ["SOAP::SOAPString", XSD::QName.new(nil, "cardNumber")]]]

  attr_accessor :lastName
  attr_accessor :firstName
  attr_accessor :middleName
  attr_accessor :group
  attr_accessor :cardNumber

  def initialize(lastName = nil, firstName = nil, middleName = nil, group = nil, cardNumber = nil)
    @lastName = lastName
    @firstName = firstName
    @middleName = middleName
    @group = group
    @cardNumber = cardNumber
  end
end

# {http://contingent.bmstu.ru/}Group
class Group
  @@schema_type = "Group"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = []

  def initialize
  end
end

# {http://contingent.bmstu.ru/}Department
class Department
  @@schema_type = "Department"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = []

  def initialize
  end
end

# {http://contingent.bmstu.ru/}Faculty
class Faculty
  @@schema_type = "Faculty"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = []

  def initialize
  end
end

# {http://contingent.bmstu.ru/}ContingentOrder
class ContingentOrder
  @@schema_type = "ContingentOrder"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = []

  def initialize
  end
end

# {http://contingent.bmstu.ru/}OrderEntity
class OrderEntity
  @@schema_type = "OrderEntity"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = []

  def initialize
  end
end

# {http://contingent.bmstu.ru/}listStudentsResponse
class ListStudentsResponse < ::Array
  @@schema_type = "Student"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = [["student", ["Student[]", XSD::QName.new(nil, "student")]]]
end

# {http://contingent.bmstu.ru/}listOrdersResponse
class ListOrdersResponse
  @@schema_type = "listOrdersResponse"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = []

  def initialize
  end
end

# {http://contingent.bmstu.ru/}getResponse
class GetResponse
  @@schema_type = "getResponse"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = [["object", ["BaseObject", XSD::QName.new(nil, "object")]]]

  attr_accessor :object

  def initialize(object = nil)
    @object = object
  end
end

# {http://contingent.bmstu.ru/}getRequest
class GetRequest
  @@schema_type = "getRequest"
  @@schema_ns = "http://contingent.bmstu.ru/"
  @@schema_element = [["id", ["SOAP::SOAPString", XSD::QName.new(nil, "id")]]]

  attr_accessor :id

  def initialize(id = nil)
    @id = id
  end
end
end
